# Dockerfile for Astro + Node.js Application

# ---- Stage 1: Install Dependencies ----
# Use the specific Node.js version from .nvmrc on Alpine Linux
FROM node:22-alpine AS deps

LABEL stage="dependencies"

# Set working directory
WORKDIR /app

# Copy package.json and lock file
# Use * for lock file to accommodate npm, yarn, or pnpm if needed later
COPY package.json package-lock.json* ./

# Install production dependencies using npm ci for faster, reliable builds
# --omit=dev ensures only production dependencies are installed
# --ignore-scripts prevents husky prepare script from running (husky is a dev dep)
RUN npm ci --omit=dev --ignore-scripts

# ---- Stage 2: Build Application ----
# Use the same base image for consistency
FROM node:22-alpine AS builder

LABEL stage="builder"

# Define build-time arguments
# PUBLIC_ENV_NAME needs to be passed during the build command
# e.g., docker build --build-arg PUBLIC_ENV_NAME=your_value -t your-image .
ARG PUBLIC_ENV_NAME

# Set environment variables available during the build
ENV NODE_ENV=production
ENV PUBLIC_ENV_NAME=${PUBLIC_ENV_NAME}

WORKDIR /app

# Copy installed dependencies from the 'deps' stage
COPY --from=deps /app/node_modules ./node_modules

# Copy the rest of the application source code
# This utilizes the .dockerignore file
COPY . .

# Run the build script defined in package.json
# This creates the production-ready 'dist' folder for standalone mode
RUN npm run build

# ---- Stage 3: Production Image ----
# Use a clean slim base image for the final stage
FROM node:22-alpine AS final

LABEL stage="production"

# Set environment variables for the runtime environment
# NODE_ENV=production enables optimizations in Node.js and frameworks
# PORT defaults to 3000, can be overridden at runtime (docker run -e PORT=...)
# HOST=0.0.0.0 is often default for Node adapters but set explicitly for clarity
ENV NODE_ENV=production
ENV PORT=3000
ENV HOST=0.0.0.0

WORKDIR /app

# The base image node:alpine already includes a 'node' user and group.
# We will use the existing user for security.

# Copy the built application output from the 'builder' stage
# The Astro Node adapter's standalone mode outputs to 'dist/'
COPY --from=builder /app/dist ./dist

# Copy production node_modules from the 'deps' stage
# The standalone server entry point likely still needs these at runtime
COPY --from=deps /app/node_modules ./node_modules

# Set ownership of the application files to the existing non-root user 'node'
# This now includes dist/ and node_modules/
RUN chown -R node:node /app

# Switch to the non-root user
USER node

# Expose the port the application listens on (matches ENV PORT default)
EXPOSE 3000

# Healthcheck to verify the application is running
# Uses wget (available in alpine) to check the server response
# Adjust the path if your app has a specific healthcheck endpoint (e.g., /health)
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
  CMD wget --quiet --tries=1 --spider http://localhost:${PORT}/ || exit 1

# Default command to start the Node.js server
# Executes the entry point generated by the Astro Node adapter
CMD ["node", "dist/server/entry.mjs"]
